version: '2'
services:
    db:
        image: mysql
        volumes:
            - "./db:/db"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    web:
        depends_on:
            - db
        image: test:rails-test
        volumes:
            - ".:/myapp"
        build: .
        links:
            - "db:db"
        restart: always
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
