#!/bin/sh

#DIR=`basename $(pwd)`
DIR=$(echo "`basename $(pwd)`" | sed 's/[^a-zA-Z0-9]//g')
CONTAINER_NAME="`echo $DIR`_dev"
CONTAINER_ID=$(docker ps -aq --filter="name=$CONTAINER_NAME")

#echo "CONTAINER_NAME = $CONTAINER_NAME"
#echo "CONTAINER_ID = $CONTAINER_ID"

if [ -z "$CONTAINER_ID" ]; then
    #echo "does not exist: create one"
    docker run -it --rm --name="$CONTAINER_NAME" \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /usr/bin/docker:/usr/bin/docker \
        -v "$(pwd)":"$(pwd)" \
        --workdir="$(pwd)" \
        arvin/dev-base
else
    #echo "exists: start and connect to it";
    docker start $CONTAINER_ID && docker attach $CONTAINER_ID
fi
#docker run -it --rm --name="dev_$DIR" -v "$(pwd)":/app arvin/dev-base
#alias startdev='docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -v "$(pwd)":"$(pwd)" --workdir="$(pwd)" arvin/dev-base'
