- hosts: localhost
  tasks:
   - name: Update and upgrade apt packages
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400
     become: yes
     become_user: root

   - name: Install packages
     apt:
       name: [
         ack,
         curl,
         docker.io,
         docker-compose,
         exuberant-ctags,
         git,
         git-flow,
         gnupg2,
         groff,
         gzip,
         jq,
         mc,
         openvpn,
         python3-pip,
         python3-venv,
         psmisc,
         rake,
         rename,
         ruby,
         software-properties-common,
         sqlite,
         stow,
         tar,
         tmux,
         tmuxinator,
         tree,
         unzip,
         vim,
         wget,
         zip,
         zsh
       ]

   - name: Install GitHub Cli
     shell: |
       apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
       apt-add-repository https://cli.github.com/packages
       apt update
       apt install -y gh
     become: yes
     become_user: root
