- hosts: localhost
  tasks:
   - name: Update and upgrade apt packages
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400
     become: yes
     become_user: root

   - name: Install packages
     apt: name={{ item }} state=present
     with_items:
       - ack
       - curl
       - docker.io
       - docker-compose
       - exuberant-ctags
       - git
       - git-flow
       - gnupg2
       - groff
       - gzip
       - jq
       - links
       - mc
       - mysql-client
       - openvpn
       - packer
       - python-pip
       - psmisc
       - rake
       - rename
       - ruby
       - sqlite
       - stow
       - tar
       - tidy
       - tmux
       - tmuxinator
       - tree
       - unzip
       - vim
       - wget
       - zip
       - zsh
     become: yes
     become_user: root

   - name: Install Keybase
     shell: |
       curl -O https://prerelease.keybase.io/keybase_amd64.deb && dpkg -i keybase_amd64.deb
     become: yes
     become_user: root

   - name: Install Terraform
     shell: |
       wget "https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip" -O /tmp/terraform.zip
       unzip /tmp/terraform.zip
       rm /tmp/terraform.zip
       mv terraform /bin
     become: yes
     become_user: root

   - name: Install NVM
     shell: |
       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
     become: yes
     become_user: root

   - name: Install PHP
     shell: |
       add-apt-repository ppa:ondrej/php
       apt-get update
       apt install php7.4
       apt install php-xml php-mbstring
       php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
       php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
       php composer-setup.php --install-dir=bin --filename=composer
       php -r "unlink('composer-setup.php');"
     become: yes
     become_user: root

   - name: Install AWS
     shell: |
       pip install awscli
     become: yes
     become_user: root

   #- name: Install GCloud
     #shell: |
       #export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" \
       #&& echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
       #&& curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
       #&& apt-get update && apt-get install -yq \
          #google-cloud-sdk \
          #kubectl
     #become: yes
     #become_user: root

     #- name: Get customization
     #git:
     #repo: https://github.com/arvinatienza/tools
     #dest: /home/ubuntu/.tools
