- hosts: localhost
  tasks:
   - name: Update and upgrade apt packages
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400
     become: yes
     become_user: root

   - name: Install packages
     apt: name={{ item }} state=present
     with_items:
       - chromium-browser
       - filezilla
       - firefox
       - suckless-tools
       - tightvncserver
       - xmonad
     become: yes
     become_user: root
