FROM node:6.11.3
MAINTAINER Arvin Atienza <arvin.atienza@gmail.com>

RUN npm install -g \
    @angular/cli \
    bower \
    cordova \
    grunt-cli \
    gulp \
    nativescript \
    react \
    react-native \
    redux \
    vue-cli \
    webpack \
    yo

WORKDIR /app

CMD ["/bin/bash"]
