FROM node:8.11.4-alpine
MAINTAINER Arvin Atienza <arvin.atienza@gmail.com>

RUN npm install -g \
    @angular/cli \
    bower \
    cordova \
    firebase-tools \
    grunt-cli \
    gulp \
    nativescript \
    puppeteer-core \
    react-native \
    vue-cli \
    webpack \
    yo

WORKDIR /app

CMD ["/bin/bash"]
